server:
  port: 7009
  servlet:
    context-path: /ad-webMagic

spring:
  application:
    name: eureka-client-ad-webMagic
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_ad_data?autoReconnect=true
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2


