server:
  port: 9000

spring:
  application:
    name: ad-geteway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /imooc
#  对单个微服务的转发
  routes:
    sponsor:
#      对统一的路径的微服务统一转发    context-path ?号匹配任意字符
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false

